### PR TITLE
fix Download filename

### PR DESCRIPTION
**Pull request by midzer**
Hi again,

this is a fix for https://github.com/shimberger/gohls/issues/60

I hope you're okay with rearranging those `imports` because my IDE supports me in formatting.

Have a nice week
midzer

### CODE REVIEW

**Comment by shimberger** [comment]
Thanks 👍 This is great. My IDE does the same, haven't touched the file in a long while ;)

**Comment by midzer** [comment]
Do you mind adding "hacktoberfest" topic to repo or "hacktoberfest-accepted" label to each of my PRs?

Thanks!

**Review by alai04 — COMMENTED** [review]
use %q instead of \"%s\"

**Comment by shimberger** [comment]
@alai04 Good feedback, thanks. I'll look into it on the weekend.

**Pull request merged**
