### PR TITLE
add feature of partial download

### PR DESCRIPTION
**Pull request by alai04**
When I use a browser to watch video files, sometimes I want to download some video clips instead of the entire video file. So I add this partial download feature to gohls.
In ```http_download.go```, I add GET request like this:
```GET http://localhost:8080/api/download/.../video_file01.mp4?start=300&duration=60```
to download video clip from 5min to 6min (start at 300sec with 60sec duration)
In ```ui/src/Components/Video.tsx```, I add a Switch ```Partial Download```. When it is switched on, two TextFields,  ```Start at``` and ```Duration```, will be shown.
I am not familiar with @material-ui, sorry for the UI does not look good.

### CODE REVIEW

**Comment by shimberger** [comment]
Hey, thanks so much for the pull request. I like the feature but I am not quite sure about the UI. I noticed the Video player page does not have any actions. My Idea is to put a menu in the top right corner (https://s3-eu-west-1.amazonaws.com/captured-krxvuizy1557lsmzs8mvzdj4/r5gu7-20181124-24100851.jpg) (https://material-ui.com/demos/menus/ -  the one with the 3 dots) which then has two actions: Download Video and Download Clip. Download clip would basically open a dialog (https://material-ui.com/demos/dialogs/) with the two text inputs and a download button. This way we keep the UI a bit more tidy. Would this serve your use case? If so: Are you interested in re-working the UI or do you have another Idea? No worries if not. I'll try to get around to adding the menu (it would be nice to have the download action available on playback page anyway).

**Comment by shimberger** [comment]
Hey, looks good :) Thanks so much. Can you maybe remove the old code from the Video.tsx? Then I can merge this. Thanks again for taking the time.

**Comment by alai04** [comment]
It's OK

**Comment by shimberger** [comment]
@alai04 I just merged and checked the latest snapshot 👍 Thanks for your contribution

**Pull request merged**
